# Generated by Django 4.1.1 on 2022-09-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Rooms',
        ),
    ]
