# Generated by Django 4.1.1 on 2022-09-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_topic_rooms_host_messages_rooms_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
